package com.ParquetConverter;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.apache.parquet.schema.MessageType;
import org.apache.parquet.schema.PrimitiveType;
import org.apache.parquet.schema.Types;

public class TableInfoUtil {

    static class TableInfo {
        private final MessageType schema;
        private final List<Integer> pkIndices;

        public TableInfo(MessageType schema, List<Integer> pkIndices) {
            this.schema = schema;
            this.pkIndices = pkIndices;
        }

        public MessageType getSchema() {
            return schema;
        }

        public List<Integer> getPkIndices() {
            return pkIndices;
        }
    }

    public static TableInfo getTableInfo(String tableName) {
        switch (tableName) {
            case "inventory":
                return new TableInfo(
                        Types.buildMessage()
                                .optional(PrimitiveType.PrimitiveTypeName.INT32)
                                .named("inv_date_sk")
                                .optional(PrimitiveType.PrimitiveTypeName.INT64)
                                .named("inv_item_sk")
                                .optional(PrimitiveType.PrimitiveTypeName.INT64)
                                .named("inv_warehouse_sk")
                                .optional(PrimitiveType.PrimitiveTypeName.INT32)
                                .named("inv_quantity_on_hand")
                                .named("inventory_schema"),
                        Arrays.asList(0, 1, 2));
            case "call_center":
                return new TableInfo(
                        Types.buildMessage()
                                .optional(PrimitiveType.PrimitiveTypeName.INT64)
                                .named("cc_call_center_sk")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_call_center_id")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_rec_start_date")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_rec_end_date")
                                .optional(PrimitiveType.PrimitiveTypeName.INT32)
                                .named("cc_closed_date_sk")
                                .optional(PrimitiveType.PrimitiveTypeName.INT32)
                                .named("cc_open_date_sk")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_name")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_class")
                                .optional(PrimitiveType.PrimitiveTypeName.INT32)
                                .named("cc_employees")
                                .optional(PrimitiveType.PrimitiveTypeName.INT32)
                                .named("cc_sq_ft")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_hours")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_manager")
                                .optional(PrimitiveType.PrimitiveTypeName.INT32)
                                .named("cc_mkt_id")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_mkt_class")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_mkt_desc")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_market_manager")
                                .optional(PrimitiveType.PrimitiveTypeName.INT32)
                                .named("cc_division")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_division_name")
                                .optional(PrimitiveType.PrimitiveTypeName.INT32)
                                .named("cc_company")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_company_name")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_street_number")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_street_name")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_street_type")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_suite_number")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_city")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_county")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_state")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_zip")
                                .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                                .named("cc_country")
                                .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                                .named("cc_gmt_offset")
                                .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                                .named("cc_tax_percentage")
                                .named("call_center_schema"),
                        Collections.singletonList(0));
            case "catalog_page":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cp_catalog_page_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("cp_catalog_page_id")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cp_start_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cp_end_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("cp_department")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cp_catalog_number")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cp_catalog_page_number")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("cp_description")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("cp_type")
                        .named("catalog_page_schema"), Collections.singletonList(0));
            case "catalog_returns":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cr_returned_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_returned_time_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_item_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_refunded_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_refunded_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_refunded_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_refunded_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_returning_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_returning_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_returning_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_returning_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_call_center_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_catalog_page_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_ship_mode_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_warehouse_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_reason_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cr_order_number")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cr_return_quantity")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cr_return_amount")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cr_return_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cr_return_amt_inc_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cr_fee")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cr_return_ship_cost")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cr_refunded_cash")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cr_reversed_charge")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cr_store_credit")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cr_net_loss")
                        .named("catalog_returns_schema"), Arrays.asList(2, 16));
            case "catalog_sales":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cs_sold_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_sold_time_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cs_ship_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_bill_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_bill_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_bill_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_bill_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_ship_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_ship_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_ship_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_ship_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_call_center_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_catalog_page_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_ship_mode_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_warehouse_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_item_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_promo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cs_order_number")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cs_quantity")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_wholesale_cost")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_list_price")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_sales_price")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_ext_discount_amt")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_ext_sales_price")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_ext_wholesale_cost")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_ext_list_price")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_ext_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_coupon_amt")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_ext_ship_cost")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_net_paid")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_net_paid_inc_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_net_paid_inc_ship")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_net_paid_inc_ship_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("cs_net_profit")
                        .named("catalog_sales_schema"), Arrays.asList(15, 17));
            case "customer_address":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ca_address_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_address_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_street_number")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_street_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_street_type")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_suite_number")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_city")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_county")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_state")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_zip")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_country")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ca_gmt_offset")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("ca_location_type")
                        .named("customer_address_schema"), Collections.singletonList(0));
            case "customer_demographics":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("cd_demo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("cd_gender")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("cd_marital_status")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("cd_education_status")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cd_purchase_estimate")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("cd_credit_rating")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cd_dep_count")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cd_dep_employed_count")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("cd_dep_college_count")
                        .named("customer_demographics_schema"), Collections.singletonList(0));
            case "customer":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("c_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("c_customer_id")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("c_current_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("c_current_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("c_current_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("c_first_shipto_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("c_first_sales_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("c_salutation")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("c_first_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("c_last_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("c_preferred_cust_flag")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("c_birth_day")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("c_birth_month")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("c_birth_year")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("c_birth_country")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("c_login")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("c_email_address")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("c_last_review_date")
                        .named("customer_schema"), Collections.singletonList(0));
            case "date_dim":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_date_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_date")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_month_seq")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_week_seq")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_quarter_seq")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_year")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_dow")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_moy")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_dom")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_qoy")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_fy_year")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_fy_quarter_seq")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_fy_week_seq")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_day_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_quarter_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_holiday")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_weekend")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_following_holiday")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_first_dom")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_last_dom")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_same_day_ly")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("d_same_day_lq")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_current_day")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_current_week")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_current_month")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_current_quarter")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("d_current_year")
                        .named("date_dim_schema"), Collections.singletonList(0));
            case "household_demographics":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("hd_demo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("hd_income_band_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("hd_buy_potential")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("hd_dep_count")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("hd_vehicle_count")
                        .named("household_demographics_schema"), Collections.singletonList(0));
            case "income_band":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ib_income_band_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("ib_lower_bound")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("ib_upper_bound")
                        .named("income_band_schema"), Collections.singletonList(0));
            case "item":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("i_item_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_item_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_rec_start_date")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_rec_end_date")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_item_desc")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("i_current_price")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("i_wholesale_cost")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("i_brand_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_brand")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("i_class_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_class")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("i_category_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_category")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("i_manufact_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_manufact")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_size")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_formulation")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_color")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_units")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_container")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("i_manager_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("i_product_name")
                        .named("item_schema"), Collections.singletonList(0));
            case "promotion":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("p_promo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_promo_id")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("p_start_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("p_end_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("p_item_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("p_cost")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("p_response_target")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_promo_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_channel_dmail")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_channel_email")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_channel_catalog")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_channel_tv")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_channel_radio")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_channel_press")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_channel_event")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_channel_demo")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_channel_details")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_purpose")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("p_discount_active")
                        .named("promotion_schema"), Collections.singletonList(0));
            case "reason":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("r_reason_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("r_reason_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("r_reason_desc")
                        .named("reason_schema"), Collections.singletonList(0));
            case "ship_mode":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("sm_ship_mode_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("sm_ship_mode_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("sm_type")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("sm_code")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("sm_carrier")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("sm_contract")
                        .named("ship_mode_schema"), Collections.singletonList(0));
            case "store_returns":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("sr_returned_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("sr_return_time_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("sr_item_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("sr_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("sr_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("sr_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("sr_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("sr_store_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("sr_reason_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("sr_ticket_number")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("sr_return_quantity")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("sr_return_amt")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("sr_return_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("sr_return_amt_inc_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("sr_fee")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("sr_return_ship_cost")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("sr_refunded_cash")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("sr_reversed_charge")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("sr_store_credit")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("sr_net_loss")
                        .named("store_returns_schema"), Arrays.asList(2, 9));
            case "store_sales":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("ss_sold_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ss_sold_time_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ss_item_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ss_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ss_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ss_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ss_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ss_store_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ss_promo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ss_ticket_number")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("ss_quantity")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_wholesale_cost")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_list_price")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_sales_price")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_ext_discount_amt")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_ext_sales_price")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_ext_wholesale_cost")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_ext_list_price")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_ext_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_coupon_amt")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_net_paid")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_net_paid_inc_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("ss_net_profit")
                        .named("store_sales_schema"), Arrays.asList(2, 9));
            case "store":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("s_store_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_store_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_rec_start_date")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_rec_end_date")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("s_closed_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_store_name")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("s_number_employees")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("s_floor_space")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_hours")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_manager")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("s_market_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_geography_class")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_market_desc")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_market_manager")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("s_division_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_division_name")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("s_company_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_company_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_street_number")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_street_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_street_type")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_suite_number")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_city")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_county")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_state")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_zip")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("s_country")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("s_gmt_offset")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("s_tax_precentage")
                        .named("store_schema"), Collections.singletonList(0));
            case "time_dim":
                return new TableInfo(Types.buildMessage()
                        .required(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("t_time_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("t_time_id")
                        .required(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("t_time")
                        .required(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("t_hour")
                        .required(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("t_minute")
                        .required(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("t_second")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("t_am_pm")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("t_shift")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("t_sub_shift")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("t_meal_time")
                        .named("time_dim_schema"), Collections.singletonList(0));
            case "warehouse":
                return new TableInfo(Types.buildMessage()
                        .required(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("w_warehouse_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_warehouse_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_warehouse_name")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("w_warehouse_sq_ft")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_street_number")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_street_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_street_type")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_suite_number")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_city")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_county")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_state")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_zip")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("w_country")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("w_gmt_offset")
                        .named("warehouse_schema"), Collections.singletonList(0));
            case "web_page":
                return new TableInfo(Types.buildMessage()
                        .required(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wp_web_page_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("wp_web_page_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("wp_rec_start_date")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("wp_rec_end_date")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("wp_creation_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("wp_access_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("wp_autogen_flag")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wp_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("wp_url")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("wp_type")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("wp_char_count")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("wp_link_count")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("wp_image_count")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("wp_max_ad_count")
                        .named("web_page_schema"), Collections.singletonList(0));
            case "web_returns":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("wr_returned_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_returned_time_sk")
                        .required(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_item_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_refunded_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_refunded_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_refunded_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_refunded_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_returning_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_returning_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_returning_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_returning_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_web_page_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_reason_sk")
                        .required(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("wr_order_number")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("wr_return_quantity")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("wr_return_amt")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("wr_return_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("wr_return_amt_inc_tax")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("wr_fee")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("wr_return_ship_cost")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("wr_refunded_cash")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("wr_reversed_charge")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("wr_account_credit")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("wr_net_loss")
                        .named("web_returns_schema"), Arrays.asList(2, 13));
            case "web_sales":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("ws_sold_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_sold_time_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("ws_ship_date_sk")
                        .required(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_item_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_bill_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_bill_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_bill_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_bill_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_ship_customer_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_ship_cdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_ship_hdemo_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_ship_addr_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_web_page_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_web_site_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_ship_mode_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_warehouse_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_promo_sk")
                        .required(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("ws_order_number")
                        .named("web_sales_schema"), Arrays.asList(3, 17));
            case "web_site":
                return new TableInfo(Types.buildMessage()
                        .optional(PrimitiveType.PrimitiveTypeName.INT64)
                        .named("web_site_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_site_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_rec_start_date")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_rec_end_date")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_name")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("web_open_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("web_close_date_sk")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_class")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_manager")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("web_mkt_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_mkt_class")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_mkt_desc")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_market_manager")
                        .optional(PrimitiveType.PrimitiveTypeName.INT32)
                        .named("web_company_id")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_company_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_street_number")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_street_name")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_street_type")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_suite_number")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_city")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_county")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_state")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_zip")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY)
                        .named("web_country")
                        .optional(PrimitiveType.PrimitiveTypeName.BINARY) // Changed to BINARY
                        .named("web_gmt_offset")
                        .optional(PrimitiveType.PrimitiveTypeName.DOUBLE)
                        .named("web_tax_percentage")
                        .named("web_site_schema"), Collections.singletonList(0));
            default:
                return null;
        }
    }
}
